---
title: "Figure 3 plots"
author: "Martin Loza"
---

This is the main workflow to reproduce the Pseudo-batches correction plots in Figure 3.

```{r setup}
library(here)
library(patchwork)
library(Seurat)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(ggforce)
options(future.globals.maxSize = 4e10)
source(here("Functions.R"))

resultsFile <- here("Data/Figure3")
plotsFile <- here("/Figure3")
mytheme <- theme_classic() + theme(text = element_text(size = 20), legend.text=element_text(size=16))
theme_set(mytheme)
```

## Load data 

### Integrations and main Figure data

```{r}
datal <- readRDS(file = paste0(resultsFile, "/1_datal.Rds"))
scores <- readRDS(file = paste0(resultsFile, "/1_scores.RDS"))
scoresKbet <- scores$scoresKbet
scoresSilhouette <- scores$scoresSilhouette
```

#### Setup data

```{r}
# Set pseudo-batches labels 
datal <- lapply(datal, setPseudoBatchesLabels)
```

### Ovals data

```{r}
scores <- list.files(path = resultsFile, pattern = "*scores.RDS", full.names = TRUE)
scores <- lapply(scores, readRDS)
scores <- GetScores(scores = scores)
centers <- GetCenters(scores = scores)
```

## Plots

### Metrics

```{r}
methods <- names(datal)
idxUncorrected <- which(methods == "Uncorrected")
methods <- methods[-idxUncorrected]

pMetrics <-  plotMetrics(scoresKbet = scoresKbet[,methods], scoresSilhouette = scoresSilhouette[,methods], methods = methods, nudge_y = -0.01)

pMetrics <- pMetrics + geom_hline(yintercept = scoresKbet[,"Uncorrected"], linetype = "dashed", alpha = 0.5 ) +  geom_vline(xintercept = scoresSilhouette[,"Uncorrected"], linetype = "dashed", alpha = 0.5)
#pMetrics
```

### Corrections plots

#### Create corrections plots

```{r}
methods <- names(datal)
plots <- lapply(methods, function(m){
  reduction = "umap"
  return(plotCorrection(object = datal[[m]], groups = c("seurat_clusters"), reduction = reduction, label = TRUE, label.size = 6))
})
names(plots) <- methods
```

##### Create features plots

```{r}
methods <- names(datal)
plotsFeatures <- lapply(methods, function(m){
  reduction = "umap"
  return(plotFeatures(object = datal[[m]], features = c("Pseudo_batch_1", "Pseudo_batch_2"), reduction = reduction))
})
names(plotsFeatures) <- methods
```

#### Suplementary Figures plots 

```{r}
methods <- names(plots)
supFigurePlots <- lapply(methods, function(m){
  p1 = plots[[m]]$seurat_clusters + ggtitle(m, subtitle = "Clusters") + mytheme + theme(legend.position = "none")
  p2 = plotsFeatures[[m]]$Pseudo_batch_1 + ggtitle(label = "", subtitle = "Pseudo-batch 1") + mytheme + theme(legend.position = "none")
  p3 = plotsFeatures[[m]]$Pseudo_batch_2 + ggtitle(label = "", subtitle = "Pseudo-batch 2") + mytheme + theme(legend.position = "none")
  
  return(list(clusters = p1, pseudo1 = p2, pseudo2 = p3))
})
names(supFigurePlots) <- methods
```

### BioRxiv v2 

```{r fig.height=16, fig.width=24}
p0 <- patchwork::plot_spacer()

pa <- plots[["Uncorrected"]]$seurat_clusters + ggtitle("Uncorrected", subtitle = "Clusters") + mytheme + theme(aspect.ratio = 1,legend.position = "none") + Seurat::NoAxes()

pb <- plotsFeatures[["Uncorrected"]]$Pseudo_batch_1 + ggtitle(label = "", subtitle = "Pseudo-batch 1") + mytheme + theme(aspect.ratio = 1,legend.position = "none") + Seurat::NoAxes() 

pc <- plotsFeatures[["Uncorrected"]]$Pseudo_batch_2 + ggtitle(label = "", subtitle = "Pseudo-batch 2") + mytheme + theme(aspect.ratio = 1,legend.position = "none") + Seurat::NoAxes()

pd <- pMetrics + ggtitle("Metrics") + mytheme + theme(legend.position = "none")

pe <- plots[["Canek"]]$seurat_clusters + ggtitle(label = "Canek", subtitle = "Clusters") + mytheme + theme(legend.position = "none")
pf <- plotsFeatures[["Canek"]]$Pseudo_batch_1 + ggtitle(label = "", subtitle = "Pseudo-batch 1") + mytheme + theme(legend.position = "none")
pg <- plotsFeatures[["Canek"]]$Pseudo_batch_2 + ggtitle(label = "", subtitle = "Pseudo-batch 2") + mytheme + theme(legend.position = "none")

ph <- plots[["MNN"]]$seurat_clusters + ggtitle(label = "MNN", subtitle = "Clusters") + mytheme + theme(legend.position = "none")
pi <- plotsFeatures[["MNN"]]$Pseudo_batch_1 + ggtitle(label = "", subtitle = "Pseudo-batch 1") + mytheme + theme(legend.position = "none")
pj <- plotsFeatures[["MNN"]]$Pseudo_batch_2 + ggtitle(label = "", subtitle = "Pseudo-batch 2") + mytheme + theme(legend.position = "none")

layout <- "
###ab
###ac
efgdd
hijdd
"

p <- wrap_plots(a = pa, b = pb, c = pc,
                d = pd,
                e = pe, f = pf, g = pg,
                h = ph, i = pi, j = pj,
                design = layout, widths = 1, heights = 1)

p
```


#### Supplementary Figure 

```{r fig.height=20, fig.width=24}

pUnco <- supFigurePlots[["Uncorrected"]]$clusters + supFigurePlots[["Uncorrected"]]$pseudo1 + supFigurePlots[["Uncorrected"]]$pseudo2

pCanek <- supFigurePlots[["Canek"]]$clusters + supFigurePlots[["Canek"]]$pseudo1 + supFigurePlots[["Canek"]]$pseudo2

pMNN <- supFigurePlots[["MNN"]]$clusters + supFigurePlots[["MNN"]]$pseudo1 + supFigurePlots[["MNN"]]$pseudo2

pSeurat <- supFigurePlots[["Seurat"]]$clusters + supFigurePlots[["Seurat"]]$pseudo1 + supFigurePlots[["Seurat"]]$pseudo2

pComBat <- supFigurePlots[["ComBat"]]$clusters + supFigurePlots[["ComBat"]]$pseudo1 + supFigurePlots[["ComBat"]]$pseudo2

pScanorama <- supFigurePlots[["Scanorama"]]$clusters + supFigurePlots[["Scanorama"]]$pseudo1 + supFigurePlots[["Scanorama"]]$pseudo2

pComBatseq <- supFigurePlots[["ComBatseq"]]$clusters + supFigurePlots[["ComBatseq"]]$pseudo1 + supFigurePlots[["ComBatseq"]]$pseudo2

pscMerge <- supFigurePlots[["scMerge"]]$clusters + supFigurePlots[["scMerge"]]$pseudo1 + supFigurePlots[["scMerge"]]$pseudo2

pHarmony <- supFigurePlots[["Harmony"]]$clusters + supFigurePlots[["Harmony"]]$pseudo1 + supFigurePlots[["Harmony"]]$pseudo2

pLiger <- supFigurePlots[["Liger"]]$clusters + supFigurePlots[["Liger"]]$pseudo1 + supFigurePlots[["Liger"]]$pseudo2

layout <- "
ab
cd
ef
gh
ij
"

p <- wrap_plots(a = pUnco,
                b = pCanek, 
                c = pComBat,
                d = pComBatseq,
                e = pHarmony,
                f = pLiger,
                g = pMNN,
                h = pScanorama,
                i = pscMerge,
                j = pSeurat,
                design = layout, widths = 1, heights = 1)

p
```

### Ovals 

```{r fig.width=10, fig.height=8}
p1 <- PlotOvals(p = p, scores = scores, centers = centers, alpha = 0.2, level = 0.95) + 
  geom_hline(yintercept = centers["Uncorrected", "mukBET"], linetype = "dashed", alpha = 0.5 ) +
  geom_vline(xintercept = centers["Uncorrected", "muSilhouette"], linetype = "dashed", alpha = 0.5) +
  mytheme + theme(aspect.ratio = 1)
p2 <- p1 + xlim(c(0.2, 0.27)) + ylim(0.8,1.1) 

p <- (p1 / p2) + plot_layout(guides = "collect")

p
```